<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.1" />
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.44" PrivateAssets="All" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>

  <Target Name="MergeYamlDotNetIntoGenerator" AfterTargets="Build">
    <ItemGroup>
      <InputAssemblies Include="$(TargetPath)" />
      <InputAssemblies Include="$(TargetDir)YamlDotNet.dll" />
    </ItemGroup>

    <ILRepack
      InputAssemblies="@(InputAssemblies)"
      OutputFile="$(TargetPath)"
      Internalize="true"
      LibraryPath="$(TargetDir)" />
  </Target>
</Project>
