using System.Collections.Generic;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SaintsConstSourceGenerator
{
    public class MSortingLayers
    {
        public string name;

        public uint uniqueID;
        // public int locked;
    }

    public class TagManager
    {
        public string[] tags;
        public string[] layers;
        public MSortingLayers[] m_SortingLayers;
        public string[] m_RenderingLayers;
    }

    public class TagManagerYaml
    {
        public TagManager TagManager;
    }

    public static class TagManagerParser
    {
        // private readonly struct LayerInfo
        // {
        //     public readonly string Key;
        //     public readonly string Name;
        //     public readonly int Index;
        //     public readonly int Mask;
        //     // public readonly bool Conflicted;
        //
        //     public LayerInfo(string key, string name, int index, int mask)
        //     {
        //         Key = key;
        //         Name = name;
        //         Index = index;
        //         Mask = mask;
        //         // Conflicted = conflicted;
        //     }
        // }

        public static void WriteTagManagerGen(TagManager tagManager, GeneratorExecutionContext context)
        {
            WriteTags(tagManager, context);
            WriteLayers(tagManager, context);
            WriteSortingLayers(tagManager, context);
            WriteRenderingLayers(tagManager, context);
        }

        #region Tags
        private static void WriteTags(TagManager tagManager, GeneratorExecutionContext context)
        {
            Utils.DebugToFile($"found tags {string.Join(", ", tagManager.tags)}");
            HashSet<string> conflictedSet = new HashSet<string>();
            HashSet<string> existsName = new HashSet<string>();
            StringBuilder tagFieldsBuilder = new StringBuilder();

            List<string> tagsWithDefault = new List<string>
            {
                "Respawn",
                "Finish",
                "EditorOnly",
                "MainCamera",
                "Player",
                "GameController",
            };
            tagsWithDefault.AddRange(tagManager.tags);

            foreach (string tag in tagsWithDefault)
            {
                if (!string.IsNullOrEmpty(tag) && tag.Length != 0)
                {
                    string key = Utils.ProperVarName(tag);
                    bool conflicted = !existsName.Add(key);
                    if(conflicted)
                    {
                        Utils.DebugToFile($"Tag `{tag}` has conflict programming name `{key}`, skip");
                        conflictedSet.Add(tag);
                    }
                    else
                    {
                        tagFieldsBuilder.Append(string.Format(
                            TagFieldTemplate,
                            key,
                            tag,
                            tag == key
                                ? ""
                                : string.Format(TagFieldCommentTemplate, tag)));
                    }
                }
            }

            string conflictLine = "";
            // Utils.DebugToFile($"processing conflictLine");
            if (conflictedSet.Count > 0)
            {
                // Utils.DebugToFile($"conflictedSet.Count={conflictedSet.Count}");
                conflictLine = "\n    /// <summary>\n" +
                               $"    /// WARNING: conflict layer mask name found: {string.Join(", ", conflictedSet)}\n" +
                                "    /// </summary>";
            }
            // Utils.DebugToFile($"conflictLine={conflictLine}");

            string fileContent = string.Format(TagConstTemplate, conflictLine, tagFieldsBuilder);
            // Utils.DebugToFile($"content={fileContent}");

            context.AddSource("TagConst.generated.cs",
                SourceText.From(fileContent, Encoding.UTF8));
        }

        private const string TagConstTemplate = @"
// Generated by SaintsConst. Do not modify.

// ReSharper disable once CheckNamespace
namespace SaintsConst
{{{0}
    public static class TagConst
    {{
{1}
    }}
}}
";
        #endregion

        private const string TagFieldCommentTemplate = @"
        /// <summary>
        /// {0}
        /// </summary>";
        private const string TagFieldTemplate = @"
        // ReSharper disable once InconsistentNaming{2}
        public const string {0} = ""{1}"";
";

        #region Layers
        private static void WriteLayers(TagManager tagManager, GeneratorExecutionContext context)
        {
            StringBuilder nameFieldsBuilder = new StringBuilder();
            StringBuilder indexFieldsBuilder = new StringBuilder();
            StringBuilder maskFieldsBuilder = new StringBuilder();

            HashSet<string> conflictedSet = new HashSet<string>();

            HashSet<string> existsName = new HashSet<string>();
            for (int index = 0; index < tagManager.layers.Length; index++)
            {
                string layerName = tagManager.layers[index];
                // Utils.DebugToFile($"LayerName {layerName}");
                if (!string.IsNullOrEmpty(layerName) && layerName.Length != 0)
                {
                    string key = Utils.ProperVarName(layerName);
                    bool conflicted = !existsName.Add(key);
                    if(conflicted)
                    {
                        // Utils.DebugToFile($"Layer `{layerName}` has conflict programming name `{key}`, skip");
                        conflictedSet.Add(layerName);
                    }
                    else
                    {
                        // Utils.DebugToFile($"Layer {layerName}");
                        int mask = 1 << index;
                        // Utils.DebugToFile($"Layer {layerName} mask {mask}");

                        nameFieldsBuilder.Append(string.Format(LayersNameFieldTemplate, key, layerName, index, mask));
                        indexFieldsBuilder.Append(string.Format(LayersIndexFieldTemplate, key, layerName, index, mask));
                        maskFieldsBuilder.Append(string.Format(LayersMaskFieldTemplate, key, layerName, index, mask));
                        // Utils.DebugToFile($"Layer {layerName} done");
                    }

                    // LayerInfo layerInfo = new LayerInfo(key, layerName, index, mask);
                }
            }

            string conflictLine = "";
            // Utils.DebugToFile($"processing conflictLine");
            if (conflictedSet.Count > 0)
            {
                // Utils.DebugToFile($"conflictedSet.Count={conflictedSet.Count}");
                conflictLine = "\n    /// <summary>\n" +
                               $"    /// WARNING: conflict layer mask name found: {string.Join(", ", conflictedSet)}\n" +
                                "    /// </summary>";
            }
            // Utils.DebugToFile($"conflictLine={conflictLine}");

            string fileContent = string.Format(LayerConstTemplate, conflictLine, nameFieldsBuilder, indexFieldsBuilder, maskFieldsBuilder);
            // Utils.DebugToFile($"content={fileContent}");

            context.AddSource("LayerConst.generated.cs",
                SourceText.From(fileContent, Encoding.UTF8));
        }

        private const string LayerConstTemplate = @"
// Generated by SaintsConst. Do not modify.

// ReSharper disable once CheckNamespace
namespace SaintsConst
{{{0}
    public static class LayerConst
    {{
        public static class Name 
        {{
{1}
        }}
        public static class Index 
        {{
{2}
        }}
        public static class Mask 
        {{
{3}
        }}
    }}
}}
";

        private const string LayersNameFieldTemplate = @"
            // ReSharper disable once InconsistentNaming
            /// <summary>
            /// Name=`{1}` Index={2} Mask={3}
            /// </summary>
            public const string {0} = ""{1}"";
";
        private const string LayersIndexFieldTemplate = @"
            /// <summary>
            /// Name=`{1}` Index={2} Mask={3}
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const int {0} = {2};
";
        private const string LayersMaskFieldTemplate = @"
            /// <summary>
            /// Name=`{1}` Index={2} Mask={3}
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const int {0} = 1 << {2};
";
        #endregion

        #region SortingLayers

        private static void WriteSortingLayers(TagManager tagManager, GeneratorExecutionContext context)
        {
            if (tagManager.m_SortingLayers == null || tagManager.m_SortingLayers.Length == 0)
            {
                return;
            }

            StringBuilder nameFieldsBuilder = new StringBuilder();
            StringBuilder idFieldsBuilder = new StringBuilder();

            HashSet<string> conflictedSet = new HashSet<string>();

            HashSet<string> existsName = new HashSet<string>();
            for (int index = 0; index < tagManager.m_SortingLayers.Length; index++)
            {
                MSortingLayers sortingLayer = tagManager.m_SortingLayers[index];
                long rawId = sortingLayer.uniqueID;
                int id = rawId > int.MaxValue
                    ? (int) (rawId - 1L << 32)
                    : (int) rawId;
                string key = Utils.ProperVarName(sortingLayer.name);
                bool conflicted = !existsName.Add(key);
                if(conflicted)
                {
                    // Utils.DebugToFile($"SortingLayer `{sortingLayer}` has conflict programming name `{key}`, skip");
                    conflictedSet.Add(sortingLayer.name);
                }
                else
                {
                    nameFieldsBuilder.Append(string.Format(
                        SortingLayerNameTemplate,
                        key,
                        sortingLayer.name,
                        key == sortingLayer.name
                            ? ""
                            : string.Format(SortingLayerNameCommentTemplate, sortingLayer.name)));
                    idFieldsBuilder.Append(string.Format(
                        SortingLayerIdTemplate,
                        key,
                        id,
                        sortingLayer.name));
                }
            }

            string conflictLine = "";
            // Utils.DebugToFile($"processing conflictLine");
            if (conflictedSet.Count > 0)
            {
                // Utils.DebugToFile($"conflictedSet.Count={conflictedSet.Count}");
                conflictLine = "\n    /// <summary>\n" +
                               $"    /// WARNING: conflict layer mask name found: {string.Join(", ", conflictedSet)}\n" +
                                "    /// </summary>";
            }
            // Utils.DebugToFile($"conflictLine={conflictLine}");

            string fileContent = string.Format(SortingLayerConstTemplate, conflictLine, nameFieldsBuilder, idFieldsBuilder);
            // Utils.DebugToFile($"content={fileContent}");

            context.AddSource("SortingLayerConst.generated.cs",
                SourceText.From(fileContent, Encoding.UTF8));
        }

        private const string SortingLayerConstTemplate = @"
// Generated by SaintsConst. Do not modify.

// ReSharper disable once CheckNamespace
namespace SaintsConst
{{{0}
    public static class SortingLayerConst
    {{

        public static class Name
        {{
            {1}
        }}

        public static class Id
        {{
            {2}
        }}

    }}
}}
";
        private const string SortingLayerNameCommentTemplate = @"
            /// <summary>
            /// {0}
            /// </summary>";
        private const string SortingLayerNameTemplate = @"
            // ReSharper disable once InconsistentNaming{2}
            public const string {0} = ""{1}"";
";
        private const string SortingLayerIdTemplate = @"
            /// <summary>
            /// {2}
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const int {0} = {1};
";
        #endregion

        #region RenderingLayers
        private static void WriteRenderingLayers(TagManager tagManager, GeneratorExecutionContext context)
        {
            if (tagManager.m_RenderingLayers == null || tagManager.m_RenderingLayers.Length == 0)
            {
                return;
            }

            HashSet<string> conflictedSet = new HashSet<string>();
            HashSet<string> existsName = new HashSet<string>();
            StringBuilder renderingLayersNameFieldsBuilder = new StringBuilder();
            StringBuilder renderingLayersMaskFieldsBuilder = new StringBuilder();

            for (int index = 0; index < tagManager.m_RenderingLayers.Length; index++)
            {
                string renderingLayer = tagManager.m_RenderingLayers[index];
                if (!string.IsNullOrEmpty(renderingLayer) && renderingLayer.Length != 0)
                {
                    string key = Utils.ProperVarName(renderingLayer);
                    bool conflicted = !existsName.Add(key);
                    if (conflicted)
                    {
                        // Utils.DebugToFile(
                        //     $"RenderingLayer `{renderingLayer}` has conflict programming name `{key}`, skip");
                        conflictedSet.Add(renderingLayer);
                    }
                    else
                    {
                        int mask = 1 << index;
                        renderingLayersNameFieldsBuilder.Append(string.Format(
                            RenderingLayerNameFieldTemplate,
                            key,
                            renderingLayer,
                            mask));
                        renderingLayersMaskFieldsBuilder.Append(string.Format(
                            RenderingLayerMaskFieldTemplate,
                            key,
                            index,
                            renderingLayer,
                            mask));
                    }
                }
            }

            string conflictLine = "";
            // Utils.DebugToFile($"processing conflictLine");
            if (conflictedSet.Count > 0)
            {
                // Utils.DebugToFile($"conflictedSet.Count={conflictedSet.Count}");
                conflictLine = "\n    /// <summary>\n" +
                               $"    /// WARNING: conflict layer mask name found: {string.Join(", ", conflictedSet)}\n" +
                                "    /// </summary>";
            }
            // Utils.DebugToFile($"conflictLine={conflictLine}");

            string fileContent = string.Format(RenderingLayerConstTemplate, conflictLine, renderingLayersNameFieldsBuilder, renderingLayersMaskFieldsBuilder);
            // Utils.DebugToFile($"content={fileContent}");

            context.AddSource("RenderingLayerConst.generated.cs",
                SourceText.From(fileContent, Encoding.UTF8));
        }

        private const string RenderingLayerConstTemplate = @"
// Generated by SaintsConst. Do not modify.

// ReSharper disable once CheckNamespace
namespace SaintsConst
{{{0}
    public static class RenderingLayerConst
    {{
        public static class Name 
        {{
{1}
        }}
        public static class Mask 
        {{
{2}
        }}
    }}
}}
";

        private const string RenderingLayerNameFieldTemplate = @"
            // ReSharper disable once InconsistentNaming
            /// <summary>
            /// Name=`{1}` Mask={2}
            /// </summary>
            public const string {0} = ""{1}"";
";
        private const string RenderingLayerMaskFieldTemplate = @"
            /// <summary>
            /// Name=`{2}` Mask={3}
            /// </summary>
            // ReSharper disable once InconsistentNaming
            public const int {0} = 1 << {1};
";
        #endregion

    }
}
